### ISSUE TITLE
Sender Email Ignored

### ISSUE THREAD

**Issue by keymandll** [eddybordi/strapi-provider-email-sendinblue#2]
I have configured `Sendinblue Default From Email`. However, it is overridden by some weird default value provided by Strapi. This is due to taking values from the `options` object by default and only using user provided data when `options` does not contain the configuration property. (lines 46-49)

The result: whatever value I provide for the fields mentioned above I end up having:

```
"sender":{"email":"\"Administration Panel\" <no-reply@strapi.io>"
```

This of course is refused by SendInBlue and I get the following error:

```
{\"code\":\"invalid_parameter\",\"message\":\"valid sender email required\"}
```

Would you consider an update not to use `options.from` but use only `config.sendinblue_default_from` to set the sender email? Alternatively, updating the documentation to provide instructions on how to override the default sender email provided by strapi?

**Comment by keymandll** [comment]
I have submitted a pull request to address the above issue. If you decide to accept the pull request, could you please bump the version number and publish the new version to npmjs? Thanks a lot.

**Comment by eddybordi** [comment]
New version updated, thanks for your pull request
